version: '2'
services:
    zoo1:
        image: zookeeper
        restart: always
        container_name: zoo1
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888 server.5=zoo5:2888:3888
        networks:
          app_net:
            ipv4_address: 172.16.238.200
            ipv6_address:  2001:3984:3989::200
        volumes:
            - ./zoo.cfg:/conf/zoo.cfg
    zoo2:
        image: zookeeper
        restart: always
        container_name: zoo2
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888 server.5=zoo5:2888:3888
        networks:
          app_net:
            ipv4_address: 172.16.238.201
            ipv6_address:  2001:3984:3989::201
        volumes:
            - ./zoo.cfg:/conf/zoo.cfg
    zoo3:
        image: zookeeper
        restart: always
        container_name: zoo3
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888 server.5=zoo5:2888:3888
        networks:
          app_net:
            ipv4_address: 172.16.238.202
            ipv6_address:  2001:3984:3989::202
        volumes:
            - ./zoo.cfg:/conf/zoo.cfg
    zoo4:
        image: zookeeper
        restart: always
        container_name: zoo4
        volumes:
            - ./zoo.cfg:/conf/zoo.cfg
        ports:
            - "2184:2181"
        environment:
            ZOO_MY_ID: 4
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888 server.5=zoo5:2888:3888
        networks:
          app_net:
            ipv4_address: 172.16.238.203
            ipv6_address:  2001:3984:3989::203
    zoo5:
        image: zookeeper
        restart: always
        container_name: zoo5
        ports:
            - "2185:2181"
        environment:
            ZOO_MY_ID: 5
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=zoo4:2888:3888 server.5=zoo5:2888:3888
        networks:
          app_net:
            ipv4_address: 172.16.238.204
            ipv6_address:  2001:3984:3989::204
        volumes:
            - ./zoo.cfg:/conf/zoo.cfg
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"